flowchart TD
	subgraph Executor
		EA[Create]
		EB[/Dispatch/]
	end

	subgraph Builder
		BA(Compute package indegrees) --> BB
		BB[Compute required subset to build target] --> BC
		BC[Queue unbuilt leaves] --> BD
		BD[Gather dependencies] --> BE
		BE[Run queued builds]
        BE --> BF(Report started event)
        BE --> BG
		BG[Create environment] --> BH
		BH[Link dependencies] --> BI
		BI[Build package] --> BJ
        BI --> EA
        BI --> EB
		BJ[Decrement parent indegrees]
		BJ --> BK(Report finished event)
		BJ --> BC
	end

	subgraph Planner
		PA(Find files in xuehua directory) --> PB
		PB[Compile lua files into chunks] --> PC
		PC[Evaluate chunks]
		PC --> PD[Package] --> PG
		PC --> PE[Namespace] --> PG
		PC --> PF[Configure] --> PG
		PG(Static package graph) --> BA
	end

	subgraph Store
		SA[Register Package] --> SC
        SB[Register Artifact] --> SC
        SC[(Registry)]
        SC --> SD(Package)
        SC --> SE(Artifact) --> SF
        SF[/Content/]
	end

	subgraph Manifest
		%% TODO: add manifest diagram
	end

	subgraph Linker
		%% TODO: add linker diagram
	end
